language: python
python:
- '2.7'
- '3.3'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- pytest
- python setup.py sdist
deploy:
  provider: releases
  api_key: 5c775edeaa83dabe97599b6420b5e9ceec432b57
  file: dist/jmms.calculadora-0.0.1.tar.gz
  on:
    repo: jmmirand/pypi_travis_test
    branch: feature/test
