language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- pytest
- python setup.py sdist
deploy:
  provider: releases
  #api_key: bb157c8f46d85333e9349a73b8c8752e3c50378e
  username: jmmirand@gmail.com
  password: Tengo.47
  file: 'dist/jmms.calculadora-0.0.2.tar.gz'
  on:
    repo: jmmirand/pypi_travis_test
    branch: feature/test
