language: python
python:
- '2.7'
- '3.3'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- pytest
- python setup.py sdist
deploy:
  provider: releases
  api_key:
    secure: PsVaoNQlNFZqThmbvW6YDLugycrE0K2BPM/wLVbntNeavoYo/d7KBWn5kukHOzNJfegfA+m2iY/pCLdrMzNZBAx9oB4up/f2klQF7SMvGDrUj2UkKsMTXAutUZ6/ydHSlElajLOFDrlf883jfhSuPD1rqoA7+I8tNFAA42yqSJyKk3nAO6txCtW18HDkXDy2uSs59yzwnOl0aAktrrxj77A/P99RHCCeJUvZjNfSXH78pkLTs+d1DDcLBZD/cxPVHkP1Um9WVEyqyg0v8nKCH59lH9plGhOsePE20DfYYInPDIuiSwsKCcQkU99CksrCZP1Um9RzkvrkbfROt7w/yz9p5LCPbhdKBHEformgI+XfC1FFeNpGzi+jKLEHNZvr4UoH2A0ZqaDoKBGaExGM29RLAa9q+LpDkvtvcoszb9R9lSSeiGhyQob2ric51PisVXTkJwlUoA0uWFaVuryXmLQGyesFgtmp0YiGi81MIsgoD6cInIjV/MPdSbDCH0Z+U0Y7F5NoanwTX4uzfHHLrWVfcjsQgvqFL33yzK4Rje8fHGoTjpW3jkt4ehe21Ubbz6zMe+QdXSU2qLTmH75M2hb0OELzfT3VhlM5GVXIuoeHuEX1RXQ37pVPMma2NDUgi03lLtJk7P87qnyGmJby4Dggtd8ne874cxLb5g69XHE=
  file: dist/jmms.calculadora-0.0.1.tar.gz
  on:
    repo: jmmirand/pypi_travis_test
    branch: feature/test
