language: python
python:
- '2.7'
- '3.3'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- pytest
- python setup.py sdist
deploy:
  provider: releases
  api_key:
    secure: ASu4l4eijO+bFKyg/3u0fiktOuXTj9KondfHbYyMl3d8uJpGjjdENftKceAVWdS9Ksa/0sPqlcAv0w2Ysdgzqxx31REZONEa6hU4r2JLB9/bRsMQzGWDzZnHHFrUFxHGsqcaVfF9+Swz4hPdbdA/89DgcXpNASs9trcNAGW5irU8FQFp3ihTv1AVR3FlvsqHzHGzdL6p/n3Ma6dG92F1aKPz247Ti9fstJatHY9WTWXoZHMQrBT5o1cRLXqIpz1i2mZrMqg73AQOfu8vWO1EdbwJ59fTFA1rM2QV1vypHY8agnbH/ZZdfH0SHv9BUno7gLQ1wjClZLRv0AjLKUhy0j/JuN0OvM/F990owJ82aBSDXaDx/o6P7ifOxsRhYvi40fC3AfjxUyQm+MhDQ/j+7XAo+80QRQA5h5HayH0Q3i0djAPT590OFOzUpAX5qTPZ/c7yzUibRtOCrtlYhqyGAUvnmprwxO7lMuItqFhS5VfWW1/AKMZ7sk2b917zoRSScpXLLj4+jBZBPi9qLH4HAaJg1CeMS+zQLW2Qb5FBMgn6OrgMQ1fV/V+OSAObdCe2t2lsVS5kw3oucZvloKVldhzwFSXH3ZJU18cs2uqL7Z4voHqIB5lO0A8SgJ5gWQrb8sZgPEHA13G8uazYjeV09/h8IBNdU7T7RW4dHJ/lQhc=
  file: dist/jmms.calculadora-0.0.1.tar.gz
  on:
    repo: jmmirand/pypi_travis_test
    branch: feature/test
