language: python
python:
- '2.7'
- '3.3'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- pytest
- python setup.py sdist
deploy:
  provider: releases
  api_key:
    secure: "r5j3H8YRfEXZmbqeHlzmABTYb/nQDqBzD53Rtgoklbgqwv3J1CXdh1TjN1gpdUjAGZSQ7LiCd6Gcc09JLbLDzSA0QU0OVizJFs/nb9ecH37qU3Gki91bUXGEZTRijMRSWwI89kvgi/SdGFulnM61giwx04YQ2bKPfFqV0PXNP4ILOjKBCtC7R1H3k6Kdtr/m1nnlvA6/IDlwSlGNbnY3uqAAu3rlSHmG973WxjR5JUSqychyUXcd+wB/F6EDHGdRFV5W5JX2AUNFy4oQ41iiSSZdjwLPiEv4qMlMWSWyOw2JSTzybksHqU5jvQNSQNW9cDkOSaXTZA0rH4SnH/ROWYd4MpekIQJMQ4W7Hr6OucMJnOxkiF28sQF6zAlNvTWPHdRMvyyQ4PR4OuntgxzBhXgZFtgNSbwm6tRfOzpXTmhUNYlJzGLFqwmRN29+w/NuoT9Acmj5zZe2mHkSnKIA1wo8aLinqSSFBQg64goMt6WcnxmOJgGcxQmpe3O6Q767xHfKWifgWkzDtr1io+6nLj2X+QoswEqVLE45/aFt+YjiUQnVnRwMzq57PxUGpHuZsIHNSFZaXfkh7LrrC7zh0cJBBOHhqRygvC3tDlVyawhxsOskcG5osmPyb9rpM+FCgqUm4i/ykxv5umTgQhRcYLhmb8LR06nL8jGuLQAwg0w="
  file: dist/jmms.calculadora-0.0.1.tar.gz
  on:
    repo: jmmirand/pypi_travis_test
    branch: feature/test
